### ISSUE TITLE
Bug on searching bib files

### ISSUE THREAD

**Issue by qiancy98** [vtex-soft/getmref#1]
```bib
@article{Weg75,
  author     = {Wegner, Gerd},
  title      = {{$d$}-collapsing and nerves of families of convex sets},
  journal    = {Arch. Math. (Basel)},
  fjournal   = {Archiv der Mathematik},
  volume     = {26},
  year       = {1975},
  pages      = {317--321},
  issn       = {0003-889X},
  mrclass    = {57C05 (52A05)},
  mrnumber   = {375333},
  mrreviewer = {N. Pol\'{a}kov\'{a}},
  doi        = {10.1007/BF01229745},
}
```
such entry becomes
```bib
%% Wegner, Gerd, $d$,
MRNUMBER={0288823},
}-collapsing and nerves of families of convex sets, Arch. Math. (Basel), 26, 317--321, 1975, 0003-889X
%% None
@article{Weg75,
  author     = {Wegner, Gerd},
  title      = {{$d$}-collapsing and nerves of families of convex sets},
  journal    = {Arch. Math. (Basel)},
  fjournal   = {Archiv der Mathematik},
  volume     = {26},
  year       = {1975},
  pages      = {317--321},
  issn       = {0003-889X},
  mrclass    = {57C05 (52A05)},
  mrnumber   = {375333},
  mrreviewer = {N. Pol\'{a}kov\'{a}},
  doi        = {10.1007/BF01229745},
}
```
It should be skipped!

**Comment by LolitaZT** [comment]
Hello, 

I'm sorry for such a delay, somehow I didn't receive an email with Your question.

Could You please provide the full references list or at least the one before this `Weg75`?  
From Your provided output I can see that the reference `Weg75` **was** actually skipped, but the MR number found for the previous reference was inserted in the wrong place. I would like to analyze why this happened.
After running the program, `*.log` file was created and the following should be there:
`Skipping: {Weg75} -> MR already present`

**Comment by qiancy98** [comment]
[references.getmref.zip](https://github.com/vtex-soft/getmref/files/14118458/references.getmref.zip)
This is the four files of the bib. I forget how did I run commands on these files.  Maybe I should try it later to get a minimal example.

**Comment by qiancy98** [comment]
It seems that the reason is: `{{` at the begining of the title is eaten, making the bracket unbalanced.

Also, `{H}olt-{K}lee` in the title becomes `Holt-{K}lee`: maybe it should become `Holt-Klee`? `({C}openhagen, 1995)` remains the same: maybe it should become `(Copenhagen, 1995)`. It seems that only brackets after a space are removed.

**Comment by LolitaZT** [comment]
Thank You for the sample. I was able to get the same result. Most probably the reference `VC71` has been added after GetMRef has been already used on this file and then using it again I've got the MR number of  `VC71` reference inserted in the same wrong position. I improved comments handling algorithm and it fixes the problem. Changes uploaded.
